### PR TITLE
TreeView: Bump PF core to move search field to toolbar and adjust expandAll behavior

### PR DESCRIPTION
**Pull request by gildub**
I realized a toggle seems redundant, [See comment](https://github.com/konveyor/forklift-ui/issues/35#issuecomment-915082796)

Therefore this patch helps with following:
- Bumps to latest Treeview and by doing so moves the search field to the toolbar.
- Removes `defaultAllExpanded` 
- Defaults `allExpanded` to true
- Adds `hasGuides` 

Edited by @mturley : removed annotation about fixing #35, since we still want the expand/collapse-all after https://github.com/patternfly/patternfly-react/issues/6314 is resolved.

### CODE REVIEW

**Comment by gildub** [comment]
@vconzola, could you please validate?

**Comment by vconzola** [comment]
@gildub I'm not sure what I'm looking for. What page(s) does this impact?

**Comment by gildub** [comment]
@vconzola this is for Plan Wizard step 2 of VMSelection during filtering

**Comment by vconzola** [comment]
@gildub Sorry, but I don't see what the difference is? Is the change something below the presentation layer. The Search bar looks the same to me?

**Comment by mturley** [comment]
@vconzola yes, this is a refactor under the hood due to a change in PatternFly. It gives us a slot in the toolbar to add the expand/collapse control for https://github.com/konveyor/forklift-ui/issues/35 that we didn't have before, but this PR doesn't put anything there.

**Comment by mturley** [comment]
Hmm, @gildub seeing your fix for the CI, I realize that I didn't notice the tree was collapsed by default. It looks like `allExpanded={true}` isn't working as expected. We may need to fix that and put the line back in the test that you removed.

**Comment by mturley** [comment]
@gildub I realized that this is a bug in PF, which I've opened here: https://github.com/patternfly/patternfly-react/issues/6314

Maybe we should just go back to `defaultAllExpanded` for now until this is resolved. Sorry to send you down the wrong path.

**Comment by gildub** [comment]
@mturley, no worries, bug happens ;)
I've restored `defaultAllExpanded` for now.

**Review by mturley — APPROVED** [review]
LGTM!

**Pull request merged**
