### PR TITLE
Update provider helper text

### LINKED ISSUE #250: [BZ#1899437] Add "Openshift virtualization" provider form improvements
https://bugzilla.redhat.com/show_bug.cgi?id=1899437

See BZ for details.

@vconzola

### PR DESCRIPTION
**Pull request by ibolton336**
Closes #250

### CODE REVIEW

**Comment by mturley** [comment]
@ibolton336 it looks like this includes a few of @gildub 's commits?

**Comment by ibolton336** [comment]
@mturley Fixed

**Review by mturley — APPROVED** [review]
LGTM. @vconzola when you get a chance, can you review? (the changes are in the Add Provider modal for OpenShift providers)

**Comment by vconzola** [comment]
How about for Name we say, "User specified name that will be displayed in the UI." and for URL drop the "The" at the beginning.

**Review by mturley — APPROVED** [review]

**Pull request merged**
