### PR TITLE
fix(must-gather): ensure must gather btn is disabled until migrations finish

### PR DESCRIPTION
**Pull request by seanforyou23**
This PR adds a check to ensure that a completed property exist on the vm/plan before enabling the must gather button.

Screen Shot 2021-10-07 at 5 00 42 PM

### CODE REVIEW

**Comment by aufi** [comment]
I'm okay with this as far it allows download logs for Plans completed/finished in whatever state (success, failure, cancelation, ..). I don't have env to test all these combinations, so will trust you :+1:

**Comment by apinnick** [comment]
@mturley  Is there any way to see the forklift-ui-preview with the "Get logs" button enabled?

**Comment by mturley** [comment]
@apinnick unfortunately no, that API is a little hard to mock so it's not supported in preview mode right now. If you need screenshots I can send them, or I can find a cluster for you to look at

**Comment by apinnick** [comment]
@mturley Thanks. I thought that might be the issue. No need. 

I wrote up a "flow" and asked Maayan to check it, since the final UI is different from Vince's mockups.

**Pull request merged**
