### PR TITLE
[QE] Infra for the edit mappings

### PR DESCRIPTION
**Pull request by kpunwatk**
1. Removed selectProvider and added selectFromDroplist for both selectSourceProvider and selectTargetProvider
2. In config's vmware and rhv added edit mapping data for both network and storage
3. Added new selectors for  selectSourceProvider,  selectTargetProvider and removed selectProvider selector
	modified:   pkg/qe-tests/cypress/integration/models/mapping.ts
	modified:   pkg/qe-tests/cypress/integration/tests/vmware/config_separate_mapping.ts
	modified:   pkg/qe-tests/cypress/integration/types/constants.ts
	modified:   pkg/qe-tests/cypress/integration/views/mapping.view.ts

### CODE REVIEW

**Comment by kpunwatk** [comment]
@ibragins Please review this PR, Thanks in advance !

**Review by sshveta — APPROVED** [review]
Looks good to me .

**Review by ibragins — APPROVED** [review]
LGTM

**Comment by kpunwatk** [comment]
Thank You @sshveta and @ibragins for the review !

**Pull request merged**
